# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kafka_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kafka_message.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13kafka_message.proto\"\x1b\n\x0cKafkaMessage\x12\x0b\n\x03img\x18\x01 \x02(\x0c')
)




_KAFKAMESSAGE = _descriptor.Descriptor(
  name='KafkaMessage',
  full_name='KafkaMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='KafkaMessage.img', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=50,
)

DESCRIPTOR.message_types_by_name['KafkaMessage'] = _KAFKAMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KafkaMessage = _reflection.GeneratedProtocolMessageType('KafkaMessage', (_message.Message,), dict(
  DESCRIPTOR = _KAFKAMESSAGE,
  __module__ = 'kafka_message_pb2'
  # @@protoc_insertion_point(class_scope:KafkaMessage)
  ))
_sym_db.RegisterMessage(KafkaMessage)


# @@protoc_insertion_point(module_scope)
